# Linux config
gui:
  theme:
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - default
    cherryPickedCommitBgColor:
      - yellow
    cherryPickedCommitFgColor:
      - black
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
keybinding:
  universal:
    quit: '<c-q>'
    return: 'q'
