# Linux config
gui:
  theme:
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - default
    cherryPickedCommitBgColor:
      - yellow
    cherryPickedCommitFgColor:
      - black
keybinding:
  universal:
    quit: '<c-q>'
    return: 'q'
