# Mac config
gui:
  theme:
    activeBorderColor:
      - yellow
      - bold
    selectedLineBgColor:
      - default
    cherryPickedCommitBgColor:
      - black
    markedBaseCommitBgColor:
      - black
  border: single
  nerdFontsVersion: '3'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  mainBranches:
    - main
    - mainline
    - master
keybinding:
  universal:
    quit: '<c-q>'
    return: 'q'
os:
  editPreset: nvim
