#!/usr/bin/env sh

limelight -m config width 2
limelight -m config radius 8
limelight -m config placement exterior
limelight -m config active_color 0xFF99d59d
limelight -m config normal_color 0x00FFFFFF

echo "limelight configuration loaded."
