#!/bin/bash

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

FONT="Lilex"
SYMBOL_FONT="SF Pro"

# General bar appearance
# For all options see https://felixkratz.github.io/SketchyBar/config/bar.
bar=(
    height=40
    color=$BAR_COLOR
    border_width=2
    border_color=$BAR_BORDER_COLOR
	shadow=off
	position=top
	sticky=on
	padding_right=10
	padding_left=10
	topmost=window
)

sketchybar --bar "${bar[@]}"

# Default values
# For a full list of all available item properties see https://felixkratz.github.io/SketchyBar/config/items.
defaults=(
	updates=when_shown
	icon.font="$SYMBOL_FONT:Semibold:15.0"
	icon.color=$ICON_COLOR
	icon.padding_left=4
	icon.padding_right=4
	label.font="$FONT:Medium:15.0"
	label.color=$LABEL_COLOR
	label.padding_left=4
	label.padding_right=4
	padding_right=5
	padding_left=5
	background.height=26
	background.corner_radius=9
	background.border_width=2
	popup.background.border_width=2
	popup.background.corner_radius=9
	popup.background.border_color=$POPUP_BORDER_COLOR
	popup.background.color=$POPUP_BACKGROUND_COLOR
	popup.blur_radius=20
	popup.background.shadow.drawing=on
	scroll_texts=on
)

sketchybar --default "${defaults[@]}"

################################################################################
#                                Left side
################################################################################

# Show the Apple logo.
# On click, show preferences, activity, and lock screen.
source "$ITEM_DIR/apple.sh"

# Show the name and icon of the app currently focused.
source "$ITEM_DIR/front_app.sh"

################################################################################
#                                 Center
################################################################################

# Show floating window when Spotify is playing a song.
source "$ITEM_DIR/spotify.sh"

################################################################################
#                                Right side
################################################################################

source "$ITEM_DIR/calendar.sh"

source "$ITEM_DIR/battery.sh"

# Left click to change volume. Right click to switch audio sources.
source "$ITEM_DIR/volume.sh"

################################################################################

##### Force all scripts to run the first time (never do this in a script). #####
sketchybar --update

echo "sketchybar configuration loaded"
