# vim:ft=kitty

## name: Inklight
## license: MIT
## author: Matthew Laufer
## upstream: https://github.com/mjlaufer/inklight.nvim/raw/main/extras/kitty/kitty_inklight.conf


background #f2f2f2
foreground #1b1b1b
selection_background #d3eef4
url_color #0049b1
cursor #1b1b1b
cursor_text_color #f2f2f2

# Tabs
active_tab_background #387200
active_tab_foreground #f2f2f2
inactive_tab_background #d7d7d7
inactive_tab_foreground #1b1b1b

# Black
color0 #f2f2f2
color8 #6e6e6e

# Red
color1 #b61e00
color9 #d02300

# Green
color2 #387200
color10 #438500

# Yellow
color3 #b65f00
color11 #c96900

# Blue
color4 #0049b1
color12 #436aaa

# Magenta
color5 #9b1b60
color13 #ac4b78

# Cyan
color6 #007585
color14 #008698

# White
color7 #1b1b1b
color15 #f2f2f2
